baseurl = "https://blog.kilian.io/"
languageCode = "en"
title = "blog.kilian.io"
theme = "hemingway"
publishDir = "docs"

[permalinks]
post = "/:slug/"

[params.highlight]
style = "github"
languages = ["go", "ruby", "swift", "javascript", "bash"]

[[params.social]]
url = "https://github.com/kiliankoe"
fa_icon = "fa-brands fa-github"

[[params.social]]
url = "https://chaos.social/@kilian"
fa_icon = "fa-brands fa-mastodon"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
